<a href="https://colab.research.google.com/github/aniket9608/Machine_learning_practice/blob/main/campusX_Encoding_cat_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.shape

(100, 6)

In [5]:
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [8]:
X_train

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
47   18  Female  104.0    Mild  Bangalore
36   38  Female  101.0    Mild  Bangalore
55   81  Female  101.0    Mild     Mumbai
21   73    Male   98.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
64   42    Male  104.0    Mild     Mumbai
34   74    Male  102.0    Mild     Mumbai
27   33  Female  102.0  Strong      Delhi
99   10  Female   98.0  Strong    Kolkata
62   56  Female  104.0  Strong  Bangalore

[80 rows x 5 columns]

## **Encoding categorical data**

categorical to numerical columns cahenges differently

In [9]:
# Adding Simple Imputer
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.fit_transform(X_test[['fever']])

In [12]:
X_train_fever.shape

(80, 1)

In [13]:
# Ordinal encoder
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])

X_test_cough=oe.fit_transform(X_test[['cough']])

In [14]:
X_train_cough.shape

(80, 1)

In [15]:
# One hot Encoding

ohe=OneHotEncoder(drop='first',sparse_output=False)

X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])

In [17]:
X_train_gender_city.shape

(80, 4)

In [20]:
# Extracting Age

X_train_age=X_train.drop(columns=['gender','city','cough','fever']).values
X_test_age=X_test.drop(columns=['gender','city','cough','fever']).values

In [24]:
X_train_age.shape

(80, 1)

In [26]:
# Concatenate all tranformed columns

X_train_transformed=np.concatenate((X_train_age,X_train_gender_city,X_train_fever,X_train_cough),axis=1)

X_test_transformed=np.concatenate((X_test_age,X_test_gender_city,X_test_fever,X_test_cough),axis=1)

In [27]:
X_train_transformed.shape

(80, 7)

In [29]:
X_train_transformed

array([[ 60.        ,   1.        ,   0.        ,   1.        ,
          0.        , 103.        ,   0.        ],
       [ 18.        ,   0.        ,   0.        ,   0.        ,
          0.        , 104.        ,   0.        ],
       [ 38.        ,   0.        ,   0.        ,   0.        ,
          0.        , 101.        ,   0.        ],
       [ 81.        ,   0.        ,   0.        ,   0.        ,
          1.        , 101.        ,   0.        ],
       [ 73.        ,   1.        ,   0.        ,   0.        ,
          0.        ,  98.        ,   0.        ],
       [ 51.        ,   1.        ,   0.        ,   1.        ,
          0.        , 104.        ,   0.        ],
       [ 34.        ,   0.        ,   0.        ,   0.        ,
          1.        , 100.94366197,   1.        ],
       [ 47.        ,   0.        ,   0.        ,   0.        ,
          0.        , 100.        ,   1.        ],
       [  5.        ,   0.        ,   0.        ,   1.        ,
          0.        , 100.        ,   0.        ],
       [ 34.        ,   0.        ,   1.        ,   0.        ,
          0.        , 101.        ,   1.        ],
       [ 12.        ,   0.        ,   0.        ,   0.        ,
          0.        , 104.        ,   0.        ],
       [ 65.        ,   1.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   0.        ],
       [ 54.        ,   0.        ,   0.        ,   1.        ,
          0.        , 104.        ,   1.        ],
       [ 10.        ,   1.        ,   0.        ,   0.        ,
          0.        , 100.        ,   0.        ],
       [ 27.        ,   1.        ,   1.        ,   0.        ,
          0.        , 100.        ,   0.        ],
       [ 55.        ,   1.        ,   0.        ,   1.        ,
          0.        , 100.        ,   0.        ],
       [ 75.        ,   0.        ,   1.        ,   0.        ,
          0.        , 100.94366197,   0.        ],
       [ 59.        ,   0.        ,   1.        ,   0.        ,
          0.        ,  99.        ,   1.        ],
       [ 26.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  98.        ,   0.        ],
       [ 27.        ,   1.        ,   0.        ,   1.        ,
          0.        , 100.        ,   0.        ],
       [ 71.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  98.        ,   1.        ],
       [ 48.        ,   0.        ,   0.        ,   1.        ,
          0.        , 103.        ,   0.        ],
       [ 69.        ,   0.        ,   0.        ,   1.        ,
          0.        , 103.        ,   0.        ],
       [ 34.        ,   0.        ,   1.        ,   0.        ,
          0.        , 104.        ,   1.        ],
       [ 40.        ,   0.        ,   1.        ,   0.        ,
          0.        ,  98.        ,   1.        ],
       [ 20.        ,   0.        ,   0.        ,   0.        ,
          1.        , 100.94366197,   1.        ],
       [ 16.        ,   0.        ,   0.        ,   0.        ,
          0.        , 103.        ,   0.        ],
       [ 14.        ,   1.        ,   0.        ,   0.        ,
          0.        , 101.        ,   1.        ],
       [ 83.        ,   1.        ,   0.        ,   1.        ,
          0.        , 103.        ,   0.        ],
       [ 47.        ,   1.        ,   0.        ,   0.        ,
          0.        , 101.        ,   1.        ],
       [ 11.        ,   1.        ,   0.        ,   0.        ,
          0.        , 100.        ,   0.        ],
       [ 24.        ,   0.        ,   0.        ,   0.        ,
          0.        , 102.        ,   1.        ],
       [ 71.        ,   1.        ,   0.        ,   1.        ,
          0.        , 100.94366197,   1.        ],
       [ 82.        ,   0.        ,   0.        ,   1.        ,
          0.        , 102.        ,   1.        ],
       [ 19.        ,   0.        ,   0.        ,   0.        ,
          0.        , 100.        ,   1.        ],
       [ 49.        ,   0.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   1.        ],
       [ 81.        ,   0.        ,   0.        ,   0.        ,
          1.        ,  98.        ,   1.        ],
       [ 72.        ,   1.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   0.        ],
       [ 19.        ,   0.        ,   0.        ,   0.        ,
          1.        , 101.        ,   0.        ],
       [ 23.        ,   1.        ,   0.        ,   0.        ,
          1.        , 100.94366197,   0.        ],
       [ 49.        ,   0.        ,   1.        ,   0.        ,
          0.        , 101.        ,   0.        ],
       [ 80.        ,   1.        ,   0.        ,   0.        ,
          0.        , 100.        ,   0.        ],
       [ 19.        ,   1.        ,   1.        ,   0.        ,
          0.        , 101.        ,   0.        ],
       [ 13.        ,   0.        ,   0.        ,   1.        ,
          0.        , 100.        ,   1.        ],
       [ 14.        ,   0.        ,   0.        ,   0.        ,
          1.        ,  99.        ,   0.        ],
       [ 49.        ,   0.        ,   1.        ,   0.        ,
          0.        , 102.        ,   0.        ],
       [ 50.        ,   0.        ,   0.        ,   1.        ,
          0.        , 103.        ,   0.        ],
       [ 20.        ,   1.        ,   1.        ,   0.        ,
          0.        , 102.        ,   1.        ],
       [ 65.        ,   0.        ,   0.        ,   0.        ,
          1.        , 101.        ,   0.        ],
       [  5.        ,   0.        ,   0.        ,   0.        ,
          1.        ,  98.        ,   1.        ],
       [  5.        ,   1.        ,   0.        ,   1.        ,
          0.        , 102.        ,   0.        ],
       [ 75.        ,   0.        ,   1.        ,   0.        ,
          0.        , 104.        ,   1.        ],
       [ 65.        ,   0.        ,   0.        ,   0.        ,
          1.        ,  98.        ,   0.        ],
       [ 51.        ,   0.        ,   0.        ,   1.        ,
          0.        , 101.        ,   1.        ],
       [ 34.        ,   1.        ,   0.        ,   1.        ,
          0.        ,  98.        ,   1.        ],
       [ 69.        ,   0.        ,   0.        ,   0.        ,
          0.        , 102.        ,   0.        ],
       [ 66.        ,   1.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   1.        ],
       [ 24.        ,   1.        ,   0.        ,   1.        ,
          0.        ,  98.        ,   0.        ],
       [ 60.        ,   0.        ,   0.        ,   0.        ,
          1.        ,  99.        ,   0.        ],
       [ 15.        ,   1.        ,   1.        ,   0.        ,
          0.        , 101.        ,   0.        ],
       [ 38.        ,   1.        ,   1.        ,   0.        ,
          0.        , 100.94366197,   0.        ],
       [ 27.        ,   1.        ,   1.        ,   0.        ,
          0.        , 100.        ,   0.        ],
       [ 20.        ,   0.        ,   0.        ,   0.        ,
          0.        , 101.        ,   0.        ],
       [ 25.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  99.        ,   1.        ],
       [ 31.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  98.        ,   0.        ],
       [ 22.        ,   0.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   0.        ],
       [ 64.        ,   0.        ,   1.        ,   0.        ,
          0.        , 101.        ,   0.        ],
       [  6.        ,   0.        ,   0.        ,   1.        ,
          0.        , 104.        ,   0.        ],
       [ 17.        ,   0.        ,   0.        ,   1.        ,
          0.        , 104.        ,   0.        ],
       [ 25.        ,   1.        ,   0.        ,   0.        ,
          0.        , 104.        ,   0.        ],
       [ 46.        ,   1.        ,   0.        ,   0.        ,
          0.        , 103.        ,   1.        ],
       [ 84.        ,   0.        ,   0.        ,   0.        ,
          0.        , 100.94366197,   0.        ],
       [ 16.        ,   1.        ,   0.        ,   1.        ,
          0.        , 104.        ,   0.        ],
       [ 42.        ,   0.        ,   0.        ,   0.        ,
          0.        , 100.94366197,   1.        ],
       [ 79.        ,   1.        ,   0.        ,   1.        ,
          0.        , 100.94366197,   1.        ],
       [ 42.        ,   1.        ,   0.        ,   0.        ,
          1.        , 104.        ,   0.        ],
       [ 74.        ,   1.        ,   0.        ,   0.        ,
          1.        , 102.        ,   0.        ],
       [ 33.        ,   0.        ,   1.        ,   0.        ,
          0.        , 102.        ,   1.        ],
       [ 10.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  98.        ,   1.        ],
       [ 56.        ,   0.        ,   0.        ,   0.        ,
          0.        , 104.        ,   1.        ]])

# **Column Transformer**

all transformation happens in single line

In [30]:
from sklearn.compose import ColumnTransformer

In [34]:
transformer=ColumnTransformer(transformers=[('tnf1',SimpleImputer(),['fever']),
                                            ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                            ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
                                            ],remainder='passthrough')

In [37]:
X_trans_train=transformer.fit_transform(X_train)
X_trans_test=transformer.fit_transform(X_test)

In [38]:
X_trans_train.shape

(80, 7)

In [39]:
X_trans_test.shape

(20, 7)